image: liuchong/rustup:stable-musl

cache:
  paths:
    - target/
    - cargo/

stages:
  - build
  - test

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

build:
  stage: build
  only:
    - tags
  tags:
    - shared
  script:
    - cargo build --release
    - strip target/x86_64-unknown-linux-musl/release/allie
  artifacts:
    expire_in: 1 week
    paths:
      - target/x86_64-unknown-linux-musl/release/allie

test:
  stage: test
  only:
    - master
  tags:
    - shared
  script:
    - cargo test
  dependencies:
    - build
