image: liuchong/rustup:stable-musl

cache:
  paths:
    - target/
    - cargo/

stages:
  - build
  - test

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

build:
  stage: build
  tags:
    - shared
  script:
    - cargo build --release
  artifacts:
    expire_in: 1h
    paths:
      - target/

test:
  stage: test
  tags:
    - shared
  script:
    - cargo test
  dependencies:
    - build
